version: '3.8'
services:
  db:
    restart: always
    image: mysql:latest
    ports:
      - "${DATABASE_PORT}:3306"
      - "33060:33060"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: apalucha 
    volumes:
      - db-data:/var/lib/mysql
  
  apalucha-backend:
    restart: always
    build: ../backend/.
    ports:
      - "${DOCKER_WEB_PORT}:5000"
    env_file:
      - ../backend/.env
    environment:
      DB_ADDRESS: db
      DB_PORT: 3306
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: apalucha
    depends_on:
      - db 
  apalucha-frontend:
    restart: always
    depends_on:
      - apalucha-backend
    build: ../frontend/.
    env_file:
      - ../frontend/.env
    ports:
      - "${DOCKER_FRONTEND_PORT}:3000"
    
volumes:
  db-data: